### ISSUE TITLE
Too many serial devices connected on macOS

### ISSUE THREAD

**Issue by Hologos** [R4D0N/Node-Firmware-Flasher-For-Mac#3]
Hi, thank you for this great piece of software. Would it be possible to add a "select box" to choose required serial port? I have several devices and some of them I really can't disconnect (I'd have to uninstall/unpair them).

I manually added a line of code to add only the correct one.

<img width="1624" alt="image" src="https://user-images.githubusercontent.com/1620004/208321232-152e2295-de0e-4dd1-8664-87b9433cc855.png">

**Comment by R4D0N** [comment]
Hello, This statement in the code should not prevent you from having other devices connected. This conflict only comes up if you somehow have multiple serial devices with the same Vendor ID as Fiberpunk. I am looking to release a GUI in future however to make the process more visual. 

Hope that helps!
