### ISSUE TITLE
Webpage instructions missing

### ISSUE THREAD

**Issue by Hologos** [R4D0N/Node-Firmware-Flasher-For-Mac#4]
Without debugging it's not clear what the error is. It is required to copy `webpage` directory into project root directory.

```Preparing to Flash Node
DO NOT UNPLUG DEVICE UNTIL COMPLETE
Generating Spiff BIN file (Step 1/3)
Unable to generate spifs.bin due to:
given base directory webpage does not exist
Halting Program
```

**Comment by R4D0N** [comment]
Hello,

Yes, it is currently required to copy the webpage folder (obtained from Fiberpunk's Github) to the root directory of the the Firmware Flasher Project. I aim to change this in future to be selected via a folder prompt.

**Comment by R4D0N** [comment]
New in [version 1.0.4](https://github.com/R4D0N/R4D0N-Firmware-Flasher-for-Node/releases/tag/v1.0.4) the gui updater uses file prompts to select firmware and webpage folders. This alleviates the need for moving your firmware and webpage contents, and renaming the webpage folder.
